name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release on Windows
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          
      - name: Get version from tag
        id: version
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          
      - name: Build Windows executable
        run: |
          go build -ldflags "-s -w" -o boxtroll.exe ./cmd/boxtroll
          
      - name: Install go-msi
        run: |
          go install github.com/mh-cbon/go-msi@latest
          
      - name: Initialize go-msi templates
        shell: powershell
        run: |
          $env:PATH = "$env:GOPATH\bin;$env:PATH"
          $env:TMP = "$PWD\tmp"
          $env:TEMP = "$PWD\tmp"
          New-Item -ItemType Directory -Force -Path tmp | Out-Null
          go-msi check-json
          go-msi set-guid
          go-msi generate-templates --version ${{ steps.version.outputs.version }}
      
      - name: go-msi Check Environment
        shell: powershell
        run: |
          $env:PATH = "$env:GOPATH\bin;$env:PATH"
          go-msi check-env
          
      - name: Create MSI installer
        shell: powershell
        run: |
          $env:PATH = "$env:GOPATH\bin;$env:PATH"
          go-msi make --msi boxtroll-${{ steps.version.outputs.version }}.msi --version ${{ steps.version.outputs.version }} --arch amd64 --src $PWD --out $PWD
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          release_name: Release ${{ steps.version.outputs.tag }}
          draft: false
          prerelease: false
          
      - name: Upload MSI to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./boxtroll-${{ steps.version.outputs.version }}.msi
          asset_name: boxtroll-${{ steps.version.outputs.version }}-windows-amd64.msi
          asset_content_type: application/x-msi

